### PR TITLE
Fixes pagespeed/ngx_pagespeed#957

### PR DESCRIPTION
**Pull request by rfnx**

### CODE REVIEW

**Comment by rfnx** [comment]
I signed it ayy

**Comment by oschaaf** [comment]
Awesome. This change looks good to me, but I want to manually test a few things before I would be happy with it being merged. I expect to get back on that next monday.
Thanks!

**Comment by jeffkaufman** [comment]
This makes sense to me.  LGTM.

@oschaaf let me know when you're comfortable with it being merged?

**Comment by oschaaf** [comment]
@jeffkaufman LGTM, I'm comfortable with merging. 

Note: one system test fails on me, `Cache purge test`, but I can't relate that to this change.

**Pull request merged**
