### PR TITLE
Eliminate CHECK that fails (rarely) during the IPRO lookup.

### PR DESCRIPTION
**Pull request by oschaaf**
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1096

### CODE REVIEW

**Comment by oschaaf** [comment]
Fix confirmed on the problem site with help from @grayfolk

**Comment by jeffkaufman** [comment]
LGTM

**Comment by jeffkaufman** [comment]
@oschaaf Should this be backported to 1.9?

**Comment by jeffkaufman** [comment]
Looks like it doesn't need backporting: the code it's fixing isn't in 1.9.

**Comment by oschaaf** [comment]
No this doesn't need to be backported.

**Pull request merged**
