### PR TITLE
We were going with type-less variable

### PR DESCRIPTION
**Pull request by cppfool**
Compiling with `clang -std=c++98/03` didn't catch that `log`
didn't have any type. But `clang -std=c++11/14` did help us.
GCC also wasn't any help to warn that in following variable `log`
```
log = log_in;
```
couldn't get its rightful type.
Fix: `auto log = log_in;` needs C++11/14 but it's
good even parameter type change Install function.
If we have C++98/03
```
ngx_log_t* log = log_in;
```
works well.

### CODE REVIEW

**Comment by jeffkaufman** [comment]
The code in question is:

```
namespace {

ngx_log_t* log = NULL;
...
}  // namespace                                                                  

namespace net_instaweb {

namespace log_message_handler {

void Install(ngx_log_t* log_in) {
  log = log_in;
  ...
}

}  // namespace log_message_handler                                              

}  // namespace net_instaweb
```

Changing `log = log_in` to `ngx_log_t* log = log_in` would not do what we want: the goal of that code is to store the `log_in` pointer in the global variable `log`.

What's the error message `clang` gives?

**Comment by cppfool** [comment]
Sorry I commited out of my morning's cloudy memory rather than right from the terminal.
Actually it is a case of name lookup which results in ambiguity.
A macro expansion clash with global "log".


This is the error on my terminal:
==================================================================
make[1]: Entering directory `/home/fooldo/cppfool/buildhelp/nginx/nginx-1.6.2'
clang++ -c -pipe  -O -std=c++11 -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail  -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/chromium/src -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/google-sparsehash/src -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/protobuf/src -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/re2/src -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/out/Release/obj/gen -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/out/Release/obj/gen/protoc_out/instaweb -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/apr/src/include -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/aprutil/src/include -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/apr/gen/arch/linux/x64/include -I /home/fooldo/cppfool/workcopy/ngx_pagespeed//psol/include/third_party/aprutil/gen/arch/linux/x64/include \
		-o objs/addon/src/log_message_handler.o \		
/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc




/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc:102:3: error: reference to
      'log' is ambiguous
  log = log_in;
  ^




/usr/include/x86_64-linux-gnu/bits/mathcalls.h:109:13: note: candidate found by name lookup is 'log'
__MATHCALL (log,, (_Mdouble_ __x));
            ^
/usr/include/math.h:53:25: note: expanded from macro '__MATHCALL'
  __MATHDECL (_Mdouble_,function,suffix, args)
                        ^
/usr/include/math.h:55:22: note: expanded from macro '__MATHDECL'
  __MATHDECL_1(type, function,suffix, args); \
                     ^
/usr/include/math.h:63:31: note: expanded from macro '__MATHDECL_1'
 extern type __MATH_PRECNAME(function,suffix) args __THROW
                              ^
/usr/include/math.h:66:42: note: expanded from macro '__MATH_PRECNAME'
#define __MATH_PRECNAME(name,r) __CONCAT(name,r)
                                         ^
/usr/include/x86_64-linux-gnu/sys/cdefs.h:88:23: note: expanded from macro '__CONCAT'
#define __CONCAT(x,y)   x ## y
                        ^
/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc:41:12: note: candidate found by
      name lookup is '(anonymous namespace)::log'
ngx_log_t* log = NULL;
           ^
/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc:107:7: error: reference to
      'log' is ambiguous
  if (log->log_level >= NGX_LOG_DEBUG) {
      ^
      long
/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc:107:10: error: cannot use arrow
      operator on a type
  if (log->log_level >= NGX_LOG_DEBUG) {
         ^
/home/fooldo/cppfool/workcopy/ngx_pagespeed//src/log_message_handler.cc:107:10: error: variable
      declaration in condition must have an initializer
5 errors generated.
============================================

**Comment by jeffkaufman** [comment]
From the error message it looks like `mathcalls.h` defines a function `log` to handle natural logarithms, and then we define a `ngx_log_t*` `log` as a pointer to the global log file.  How is `mathcalls.h` getting included?

It seems like one way to fix this would be for us to just call our variable `ps_log` instead of `log`.  Does renaming all the uses of `log` in `log_message_handler.cc` fix the problem you're seeing?

**Comment by cppfool** [comment]
Renaming log into ps_log seems to have fixed the problem at hand.
But I'am saying this only after compilation. Testing has to be done yet.

/usr/include/x86_64-linux-gnu/bits/mathcalls.h might have come from
inbuilt(ubuntu's software channel) gcc's installation on my Linux-mint machine.

**Comment by cppfool** [comment]
When we plan to move with c++11/14,
code ngx_log_t* ps_log = nullptr;
might not give us surprises
as code ngx_log_t* ps_log = NULL; might.

**Comment by jeffkaufman** [comment]
If testing works ok, could you update your pull request to do the `log` to `ps_log` rename?

When we eventually move to newer versions of C++ we'll have a lot of `NULL`s to change, but lets stick with `NULL` for now.

**Comment by cppfool** [comment]
"  /usr/local/nginx/sbin/nginx -t "  is succesful. Going to http://localhost/ gives "Welcome to nginx!" messgae.
But running ngx_pagespeed/test/run_tests.sh fails in the following way:
=================

/cppfool/workcopy/ngx_pagespeed/test $ sudo ./run_tests.sh 80 8080 ../../../buildhelp/mod_pagespeed/ /usr/local/nginx/sbin/nginx
nginx: no process found
     check mkdir /home/fooldo/cppfool/workcopy/ngx_pagespeed/test/tmp
     check mkdir /home/fooldo/cppfool/workcopy/ngx_pagespeed/test/tmp/file-cache
     check test -e /home/fooldo/cppfool/workcopy/ngx_pagespeed/test/pagespeed_test.conf.template
     check_not grep @@ /home/fooldo/cppfool/workcopy/ngx_pagespeed/test/tmp/pagespeed_test.conf
FAIL
nginx: [emerg] unknown directive "set_random" in /home/fooldo/cppfool/workcopy/ngx_pagespeed/test/tmp/pagespeed_test.conf:172
With serf fetcher setup.
=========================
I don't know how directive "set_random" has been used here. This directive is not
in the list nginx directives here:
http://nginx.org/en/docs/dirindex.html
Any help? What has gone wrong?
-------
In case following help.

/usr/local/nginx/sbin/nginx -V
nginx version: nginx/1.6.2
built by clang 3.5.0 (tags/RELEASE_350/final)
configure arguments: --with-cc=clang --with-ipv6 --add-module=/home/fooldo/cppfool/workcopy/ngx_pagespeed

Thanks.

**Comment by jeffkaufman** [comment]
If you look on our [wiki/Testing](https://github.com/pagespeed/ngx_pagespeed/wiki/Testing) page there are a few other modules that we depend on for running tests, and one of those defines `set_random`.  Could you try the steps there?

**Comment by cppfool** [comment]
If we rename log as ps_log.
I fail to see reason for the following IPRO test FAIL.
----------
TIMEOUT: wget -q   --save-headers -o /tmp/mod_pagespeed_test.root/fetched_directory/wget_output.txt                                                   -O /tmp/mod_pagespeed_test.root/fetched_directory/wget/fetch_until_output.27545 http://localhost:80/mod_pagespeed_test/ipro/test_image_dont_reuse.png output in /tmp/mod_pagespeed_test.root/fetched_directory/wget/fetch_until_output.27545
/home/fooldo/cppfool/buildhelp/mod_pagespeed//src/net/instaweb/system/../automatic/system_test_helpers.sh:476: fetch_until
/home/fooldo/cppfool/buildhelp/mod_pagespeed//src/net/instaweb/system/../automatic/system_test.sh:131: source
/home/fooldo/cppfool/buildhelp/mod_pagespeed//src/net/instaweb/system/system_test.sh:14: source
/home/fooldo/cppfool/workcopy/ngx_pagespeed/test/nginx_system_test.sh:289: main
     failure at line 131
in 'In-place resource optimization'
FAIL.
With serf fetcher setup.
----------

**Pull request closed without merging**
