### PR TITLE
respect purge requests when serving ipro requests from ngx_pagespeed

### PR DESCRIPTION
**Pull request by jmarantz**
Fixes https://github.com/pagespeed/ngx_pagespeed/issues/1192

May also fix https://github.com/pagespeed/ngx_pagespeed/issues/1172

### CODE REVIEW

**Comment by oschaaf** [comment]
LGTM

**Comment by hillsp** [comment]
It make sense to move some of this Fetch stuff into a shared class (in system/)? The specific problem here was that Apache and nginx had diverged in a subtle way, whereas IsCachedResultValid isn't actually specific to either.

**Comment by jmarantz** [comment]
Yes -- sharing a common base class between NgxFetch and ApacheFetch makes a lot of sense.  Adding a TODO to (a) avoid delaying this fix and (b) that might be harder to backport due to massive changes in ApacheFetch that are not in 1.11.

**Comment by hillsp** [comment]
SGTM. It'd be nice to see the travis check pass, but I don't see anything on the UI for retry (I may lack bits).

**Comment by jmarantz** [comment]
the test I haven't committed yet proves this fix works.  Unfortunately to check in the test I need to fix some infrastructural pieces of nginx and it's way easier to do that if I submit this first.

**Pull request merged**
