### PR TITLE
Update build script to pass --skip_deps when called with --no-deps-check

### LINKED ISSUE #1459: build_ngx_pagespeed.sh should forward --skip_deps to subscripts
To avoid having to use `sudo` it would be good to be able to avoid trying to install dependencies completely. 

From https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/qoy8wHHSeWw

### PR DESCRIPTION
**Pull request by PikachuEXE**
This should fix #1459

### CODE REVIEW

**Comment by PikachuEXE** [comment]
I signed it!

**Comment by oschaaf** [comment]
(Note: CI failure on Travis is unrelated to this pull)

**Comment by PikachuEXE** [comment]
Should I re-push to trigger CI build again?

**Comment by oschaaf** [comment]
No that's ok, thanks. The CI was broken elsewhere, we're working to fix it!

**Pull request merged**
