### PR TITLE
Remove ngx_pagespeed from HTTP_FILTER_MODULES when POSITION_AUX=true

### LINKED ISSUE #1154: POSITION_AUX=true broken in nginx 1.9.11+
Setting `POSITION_AUX=true` is not working in nginx 1.9.11+. The module `ngx_pagespeed` is appearing in both `HTTP_FILTER_MODULES` and `HTTP_AUX_FILTER_MODULES `.  `ngx_pagespeed` is appearing by default in `HTTP_FILTER_MODULES`. When `POSITION_AUX=true`, the default entry needs to be removed before it is added to `HTTP_AUX_FILTER_MODULES`.

### PR DESCRIPTION
**Pull request by JoyceBabu**
Remove ngx_pagespeed from HTTP_FILTER_MODULES when POSITION_AUX=true. Fixes #1154

### CODE REVIEW

**Comment by JoyceBabu** [comment]
I have signed the CLA.

**Comment by oschaaf** [comment]
LGTM

**Comment by jmarantz** [comment]
What's the story with this CL?  Joyce: is this something you want commit?

**Comment by oschaaf** [comment]
Landing this would require a rewrite, because things have changed a lot in the code that this touches. @centminmod do you use this? @JoyceBabu do you? 

`POSITION_AUX` is an undocumented feature that is only rarely needed afaict -- so I don't think it is used a lot. If no-one here is using it, maybe we should just close this?

**Comment by JoyceBabu** [comment]
@jmarantz I am sorry, I don't recall why I had to use the `POSITION_AUX` feature. I believe it was due to https://github.com/pagespeed/ngx_pagespeed/issues/1149#issuecomment-195794246 .

@oschaaf I am now using Apache + ModPagespeed, hence the feature is not used by me. But considering the issue mentioned in the linked comment, I think there might still be valid use cases for the feature.

**Comment by oschaaf** [comment]
Closing this PR. There might be a use-case for it, but it seems rare and I'm not sure it currently is worth the effort of rewriting this to work with the current code base. Let's see if https://github.com/pagespeed/ngx_pagespeed/issues/1149#issuecomment-195794246 pops up more, if it gets traction we can revisit this.

**Pull request closed without merging**
