### PR TITLE
fix up the description in the run_tests.sh

### PR DESCRIPTION
**Pull request by crowell**
run_tests had the wrong invocation of the script in the comments. fix
that.

### CODE REVIEW

**Comment by crowell** [comment]
this also belongs in trunk-tracking once this is in here.

**Comment by oschaaf** [comment]
`PAGESPEED_TEST_HOST` can be passed in as the argument after the nginx binary though. Should we still doc that? 

```
oschaaf@ubuntu:~/code/google/nps-issue-1175/test$ grep -ir PAGESPEED_TEST_HOST
...
run_tests.sh:PAGESPEED_TEST_HOST="$5"
...
```

**Comment by crowell** [comment]
fixed and squashed.

**Comment by oschaaf** [comment]
lgtm!

**Pull request merged**
