### PR TITLE
Update mod_pagespeed testing dependency

### PR DESCRIPTION
**Pull request by oschaaf**
(mod_pagespeed commit a7c39a1b5a14f1422fef19e8e9dcb11074ba1c65)
This should make CI pass tests

### CODE REVIEW

**Comment by oschaaf** [comment]
Somehow, with this change, CI still fails on system test 'CSS minify with calc function and value 0.'. Looking into that.

**Comment by oschaaf** [comment]
Updated this to include a change that should make the tests pass

**Comment by morlovich** [comment]
LGTM, but this seems like this will be a headache a lot..

**Comment by oschaaf** [comment]
@morlovich It looks like as of git 1.8.2 it is possible to track branches.
https://stackoverflow.com/questions/9189575/git-submodule-tracking-latest.

Would be nice if we could use that, but I'm not sure if it is a good idea to assume git 1.8.2+ is available to everyone.

**Pull request merged**
