### PR TITLE
combine-ids: add configuration for system test

### PR DESCRIPTION
**Pull request by jeffkaufman**

### CODE REVIEW

**Comment by oschaaf** [comment]
LGTM, but though doesn't pass tests on my system:
```
nginx: [emerg] "pagespeed" directive "PermitIdsForCssCombining" not recognized or too many arguments in /home/oschaaf/code/google/nps-testpull/test/tmp/pagespeed_test.conf:1701
```
 (I wonder how this did pass CI tests?). I assume this depends on an upcoming change in mps?

**Comment by jeffkaufman** [comment]
Yes, sorry, this won't pass tests yet because it doesn't have the mps change that adds support for `PermitIdsForCssCombining`.

**Comment by jeffkaufman** [comment]
> I wonder how this did pass CI tests?

Looking at travis.yaml, we don't actually run the tests.  We just make sure we can build, and then echo instructions on how to run the tests.

**Comment by jeffkaufman** [comment]
(good catch!)

**Pull request merged**
