### PR TITLE
Proposed changes for releasing 1.12.34.3-stable (ngx_pagespeed only)

### PR DESCRIPTION
**Pull request by oschaaf**

### CODE REVIEW

**Comment by oschaaf** [comment]
Note: I added a significant change after testing, to amend a mistake I introduced earlier: 3a4fce0ef92cecb4f4a27c1f68306dc20c9f03ed. I'll backport that to master.

**Comment by oschaaf** [comment]
Currently running some more manual tests with this, I plan to merge this once I'm convinced we can release with these changes. Which will probably be somewhere tomorrow. After that we can retag `latest-stable`, and send out the announcement. 

@jmarantz should we also retag `latest-beta` in this case?

**Comment by jmarantz** [comment]
Yes I would not have latest-beta lag latest-stable.

**Comment by oschaaf** [comment]
The output of manually running the system tests is looking good: only the "unauth inlining" tests fail, but that was to be expected because of some recent infrastructural changes.

One issue remaining: I noticed that this emits `X-Page-Speed: 1.12.34.2-0` in the response headers. That makes sense, because that is the PSOL version we are linking in, which is where we get the version from. 

However, this may be slightly confusing, because intuitively one would expect `1.12.34.3` to show up.  I'm wondering: perhaps we should somehow distinguish between versioning of the PageSpeed optimization libraries and its derived ports.. but that probably isn't something that makes sense to do right now.

**Comment by oschaaf** [comment]
@jmarantz see my comment above, do you think we should treat emitting `X-Page-Speed: 1.12.34.2-0`  a blocker? To fix that, we'd probably also have to release a clone of mps 1.12.34.2 as 1.12.34.3 -- with a single line change to update the version header..

**Comment by oschaaf** [comment]
@jmarantz Added a change to ensure we emit the correct version: https://github.com/pagespeed/ngx_pagespeed/pull/1482/commits/04030050f8cfa8ec71b4edee4fbb197682c3187e
LGTY?

**Pull request merged**
